# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update LSG JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Dump All LSG Bodies
      run: |
        rm -rf data/*
        python lsg.py
    - name: Commit files
      run: |
        git config --global user.name 'JSON Updater'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --staged --quiet || git commit -m "Update JSON 🌍"
        git push
